package kie

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
)

// GetDownloadURL generates a temporary download URL for a KIE-generated file.
//
// The returned URL is valid for 20 minutes only. Make sure to download
// the content within this timeframe.
//
// Note: This endpoint only supports files generated by kie.ai services.
// External file URLs will result in a validation error.
//
// Example:
//
//	downloadURL, err := client.GetDownloadURL(ctx, "https://tempfile.1f6c...")
//	if err != nil {
//	    log.Fatal(err)
//	}
//
//	// Download the file
//	resp, _ := http.Get(downloadURL)
//	defer resp.Body.Close()
//	io.Copy(outputFile, resp.Body)
func (c *Client) GetDownloadURL(ctx context.Context, fileURL string) (string, error) {
	if fileURL == "" {
		return "", fmt.Errorf("kie: file URL cannot be empty")
	}

	// Prepare request body
	payload := map[string]string{
		"url": fileURL,
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return "", wrapError("failed to marshal payload", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(
		ctx,
		http.MethodPost,
		c.baseURL+"/api/v1/common/download-url",
		bytes.NewReader(body),
	)
	if err != nil {
		return "", wrapError("failed to create request", err)
	}

	// Set GetBody for retry support
	bodyCopy := make([]byte, len(body))
	copy(bodyCopy, body)
	httpReq.GetBody = func() (io.ReadCloser, error) {
		return io.NopCloser(bytes.NewReader(bodyCopy)), nil
	}

	// Execute request
	respBody, err := c.doRequest(ctx, httpReq)
	if err != nil {
		return "", err
	}

	// Parse response - data is directly the download URL (string)
	downloadURL, err := parseResponseData[string](respBody)
	if err != nil {
		return "", err
	}

	return *downloadURL, nil
}

// GetDownloadURLs generates temporary download URLs for multiple KIE-generated files.
//
// This method processes URLs concurrently for efficiency.
// Each returned URL is valid for 20 minutes.
//
// Example:
//
//	fileURLs := []string{
//	    "https://tempfile.1f6c...",
//	    "https://tempfile.2f7d...",
//	}
//	downloadURLs, err := client.GetDownloadURLs(ctx, fileURLs)
//	if err != nil {
//	    log.Fatal(err)
//	}
//
//	for i, url := range downloadURLs {
//	    fmt.Printf("File %d: %s\n", i+1, url)
//	}
func (c *Client) GetDownloadURLs(ctx context.Context, fileURLs []string) ([]string, error) {
	if len(fileURLs) == 0 {
		return nil, nil
	}

	results := make([]string, len(fileURLs))
	errors := make([]error, len(fileURLs))
	var wg sync.WaitGroup

	// Process concurrently with a semaphore to limit parallelism
	semaphore := make(chan struct{}, 5)

	for i, url := range fileURLs {
		wg.Add(1)
		go func(idx int, fileURL string) {
			defer wg.Done()

			select {
			case <-ctx.Done():
				errors[idx] = ctx.Err()
				return
			case semaphore <- struct{}{}:
				defer func() { <-semaphore }()
			}

			downloadURL, err := c.GetDownloadURL(ctx, fileURL)
			if err != nil {
				errors[idx] = err
				return
			}
			results[idx] = downloadURL
		}(i, url)
	}

	wg.Wait()

	// Check for any errors
	for i, err := range errors {
		if err != nil {
			return nil, fmt.Errorf("kie: failed to get download URL for file %d: %w", i, err)
		}
	}

	return results, nil
}

// IsKIETempFileURL checks if a URL is a KIE temporary file URL.
// These URLs require conversion via GetDownloadURL before downloading.
func IsKIETempFileURL(url string) bool {
	return strings.Contains(url, "tempfile.")
}

// wrapError wraps an error with a kie prefix.
func wrapError(msg string, err error) error {
	return fmt.Errorf("kie: %s: %w", msg, err)
}
